server:
  port: 7971

spring:
  application:
    name: xzuul3

eureka:
  instance:
    prefer-ip-address: true    #表示启用IP访问
  client:
    serviceUrl:
      defaultZone: http://192.168.25.1:8900/eureka/

zuul:
  ignoredServices: '*'      # 加需要反向代理的服务名字
  routes:
    xserver1: /cs/**     #  等同于  xserver1