server:
  port: 7961

spring:
  application:
    name: xzuul2


eureka:
  instance:
    prefer-ip-address: true    #表示启用IP访问
  client:
    serviceUrl:
      defaultZone: http://192.168.25.1:8900/eureka/

management:
  security:
    enabled: false      #关闭可以查看  routes服务