server:
  port: 7921

spring:
  application:
    name: xconsumer1

eureka:
  instance:
    prefer-ip-address: true    #表示启用IP访问
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://root:root@192.168.25.1:8900/eureka/

hystrix:
  threadpool:
    default:
      coreSize: 500  #并发执行的最大线程数，默认10
  command:
    paas-file:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3600000
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000  #命令执行超时时间，默认1000ms